const nombresBoleta = {
  "TOWER AND TOWER S.A.": "TOWER AND TOWER S.A.",
  "LABORATORIO DE INSTRUMENTOS AMBIENTALES S.A.C.": "LABORATORIO DE INSTRUMENTOS AMBIENTALES S.A.C",
  "INVERSIONES LURIN S.A.C.": "INVERSIONES LURIN S.A.C",
  "ECOLOGY RESEARCH AND MENTORING S.C.R.L.": "ECOLOGY RESEARCH AND MENTORING S.R.L",
  "CORPORACION DE EMPRESAS DE SERVICIOS SOCIEDAD ANONIMA CERRADA - CORPEMSE S.A.C": "CORPORACION DE EMPRESAS Y SERVICIOS S.A.C",
};

export const obtenerNombreEmpresaBoleta = (razonSocial) => (
  nombresBoleta[razonSocial] || razonSocial || ""
);
